package by.pvt.kish.aircompany.services.impl;

import by.pvt.kish.aircompany.constants.Message;
import by.pvt.kish.aircompany.dao.impl.UserDAO;
import by.pvt.kish.aircompany.enums.UserStatus;
import by.pvt.kish.aircompany.exceptions.DaoException;
import by.pvt.kish.aircompany.exceptions.ServiceException;
import by.pvt.kish.aircompany.exceptions.ServiceLoginException;
import by.pvt.kish.aircompany.exceptions.ServiceValidateException;
import by.pvt.kish.aircompany.pojos.User;
import by.pvt.kish.aircompany.services.BaseService;
import by.pvt.kish.aircompany.services.IUserService;
import by.pvt.kish.aircompany.validators.UserValidator;
import org.apache.log4j.Logger;

import java.util.List;

/**
 * This class represents a concrete implementation of the IUserService interface for user model.
 *
 * @author Kish Alexey
 */
public class UserService extends BaseService<User> implements IUserService {

    private static Logger logger = Logger.getLogger(UserService.class);
    private static UserService instance;
    private UserDAO userDAO = UserDAO.getInstance();
    private UserValidator userValidator = new UserValidator();

    /**
     * Returns an synchronized instance of a UserService, if the instance does not exist yet - create a new
     *
     * @return - a instance of a UserService
     */
    public synchronized static UserService getInstance() {
        if (instance == null) {
            instance = new UserService();
        }
        return instance;
    }

    /**
     * Create the user Entity
     *
     * @param user - The user object to be created
     * @return - The ID of the user object, generated by DB
     * @throws ServiceException         - if something fails at Service layer
     * @throws ServiceValidateException - if something fails at Service validation
     * @throws ServiceLoginException    - if something fails at Service user authorisation
     */
    @Override
    public Long add(User user) throws ServiceException, ServiceLoginException, ServiceValidateException {
        Long id;
        try {
            String validateResult = userValidator.validate(user);
            if (validateResult != null) {
                throw new ServiceValidateException(validateResult);
            }
            if (!userDAO.checkLogin(user.getLogin())) {
                throw new ServiceLoginException(Message.ERROR_REG_USER_EXISTS);
            } else {
                transaction = util.getSession().beginTransaction();
                id =  userDAO.add(user);
                transaction.commit();
                logger.info(SUCCESSFUL_TRANSACTION);
            }
        } catch (DaoException e) {
            transaction.rollback();
            logger.info(TRANSACTION_FAILED);
            throw new ServiceException(e);
        }
        return id;
    }

    /**
     * Update the user Entity
     *
     * @param user - The user object to be updated
     * @throws ServiceException         - if something fails at Service layer
     * @throws ServiceValidateException - if something fails at Service validation
     */
    @Override
    public void update(User user) throws ServiceException, ServiceValidateException {
        serviceUtils.updateEntity(userDAO, user, userValidator);
    }

    /**
     * Returns a list of all users
     *
     * @return a list of all users
     * @throws ServiceException - if something fails at Service layer
     */
    @Override
    public List<User> getAll() throws ServiceException {
        return serviceUtils.getAllEntities(userDAO);
    }

    /**
     * Delete the user Entity
     *
     * @param id - The ID of the user entity to be deleted
     * @throws ServiceException - if something fails at Service layer
     */
    @Override
    public void delete(Long id) throws ServiceException {
        serviceUtils.deleteEntity(userDAO, id);
    }

    /**
     * Returns the user entity matching the given ID
     *
     * @param id - The ID of the user entity to be returned
     * @return - the user entity matching the given ID
     * @throws ServiceException - if something fails at Service layer
     */
    @Override
    public User getById(Long id) throws ServiceException {
        return serviceUtils.getByIdEntity(userDAO, id);
    }

    /**
     * Checks unique login to the DB
     *
     * @param login - checked login
     * @return false is login exists, true is don`t
     * @throws DaoException If something fails at DB level
     */
    @Override
    public boolean checkLogin(String login) throws ServiceException {
        boolean result;
        try {
            transaction = util.getSession().beginTransaction();
            result = userDAO.checkLogin(login);
            transaction.commit();
            logger.info(SUCCESSFUL_TRANSACTION);
        } catch (DaoException e) {
            transaction.rollback();
            logger.info(TRANSACTION_FAILED);
            throw new ServiceException(e.getMessage());
        }
        return result;
    }

    /**
     * Returns the user from the DB matching the given login and password
     *
     * @param login    - login of the user to be returned
     * @param password - password of the user to be returned
     * @return The user from the DB matching the given login and password
     * @throws DaoException If something fails at DB level
     */
    @Override
    public User getUser(String login, String password) throws ServiceException, ServiceLoginException {
        User user;
        try {
            transaction = util.getSession().beginTransaction();
            user = userDAO.getUser(login, password);
            if (user == null) {
                throw new ServiceLoginException(Message.ERROR_REG_LOGIN);
            } else if (user.getStatus().equals(UserStatus.ONLINE)) {
                throw new ServiceLoginException(Message.ERROR_REG_USER_EXISTS);
            } else {
                userDAO.setStatus(user.getUid(), UserStatus.ONLINE);
                user.setStatus(UserStatus.ONLINE);
            }
            transaction.commit();
            logger.info(SUCCESSFUL_TRANSACTION);
        } catch (DaoException e) {
            transaction.rollback();
            logger.info(TRANSACTION_FAILED);
            throw new ServiceException(e.getMessage());
        }
        return user;
    }

    /**
     * Set user status to DB
     *
     * @param id     - The ID of the user to be set
     * @param status - The status to be set
     * @throws DaoException If something fails at DB level
     */
    @Override
    public void setStatus(Long id, UserStatus status) throws ServiceException, ServiceValidateException {
        try {
            if (id < 0) {
                throw new ServiceException(Message.ERROR_ID_MISSING);
            }
            transaction = util.getSession().beginTransaction();
            userDAO.setStatus(id, status);
            transaction.commit();
            logger.info(SUCCESSFUL_TRANSACTION);
        } catch (DaoException e) {
            transaction.rollback();
            logger.info(TRANSACTION_FAILED);
            throw new ServiceException(e.getMessage());
        }
    }
}
