package by.pvt.kish.aircompany.services.impl;

import by.pvt.kish.aircompany.dao.IUserDAO;
import by.pvt.kish.aircompany.exceptions.DaoException;
import by.pvt.kish.aircompany.exceptions.ServiceException;
import by.pvt.kish.aircompany.exceptions.ServiceLoginException;
import by.pvt.kish.aircompany.pojos.User;
import by.pvt.kish.aircompany.services.BaseService;
import by.pvt.kish.aircompany.services.IUserService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import static by.pvt.kish.aircompany.utils.ServiceUtils.checkNullUser;

/**
 * This class represents a concrete implementation of the IUserService interface for user model.
 *
 * @author Kish Alexey
 */
@Service
@Transactional(propagation = Propagation.REQUIRED)
public class UserService extends BaseService<User> implements IUserService {

    private static Logger logger = Logger.getLogger(UserService.class);

    private static final String MESSAGE_ERROR_USER_EXISTS = "ERROR_REG_USER_EXISTS";

    @Autowired
    private IUserDAO userDAO;

    /**
     * Create the user Entity
     *
     * @param user - The user object to be created
     * @return - The ID of the user object, generated by DB
     * @throws ServiceException         - if something fails at Service layer
     * @throws ServiceLoginException    - if something fails at Service user authorisation
     */
    @Override
    public User addUser(User user) throws ServiceException, ServiceLoginException {
        try {
            if (!userDAO.checkLogin(user.getLogin())) {
                throw new ServiceLoginException(MESSAGE_ERROR_USER_EXISTS);
            } else if (user != null) {
                user = userDAO.add(user);
                logger.debug(SUCCESSFUL_TRANSACTION);
            }
        } catch (DaoException e) {
            logger.debug(TRANSACTION_FAILED, e);
            throw new ServiceException(e);
        }
        return user;
    }

    /**
     * Checks unique login to the DB
     *
     * @param login - checked login
     * @return false is login exists, true is don`t
     * @throws DaoException If something fails at DB level
     */
    @Override
    @Transactional(propagation = Propagation.SUPPORTS, readOnly = true)
    public boolean checkLogin(String login) throws ServiceException {
        boolean result;
        try {
            result = userDAO.checkLogin(login);
        } catch (DaoException e) {
            throw new ServiceException(e.getMessage());
        }
        return result;
    }

    /**
     * Returns the user from the DB matching the given login and password
     *
     * @param login    - login of the user to be returned
     * @param password - password of the user to be returned
     * @return The user from the DB matching the given login and password
     * @throws DaoException If something fails at DB level
     */
    @Override
    public User getUser(String login, String password) throws ServiceException, ServiceLoginException {
        User user;
        try {
            user = userDAO.getUser(login, password);
            checkNullUser(user);
            logger.debug(SUCCESSFUL_TRANSACTION);
        } catch (DaoException e) {
            logger.debug(TRANSACTION_FAILED, e);
            throw new ServiceException(e.getMessage());
        }
        return user;
    }



    /**
     * Set user status to DB
     *
     * @param login - The login of the user
     * @throws ServiceException - if something fails at Service layer
     */
    @Override
    public User getByLogin(String login) throws ServiceException {
        User user;
        try {
            user = userDAO.getByLogin(login);
            checkNullUser(user);
            logger.debug(SUCCESSFUL_TRANSACTION);
        } catch (ServiceLoginException e) {
            logger.debug(TRANSACTION_FAILED, e);
            throw new ServiceException(e.getMessage());
        }
        return user;
    }

    /**
     * Create the given Entity
     *
     * @param user - object to be created
     * @return - The ID of the object, generated by DB
     * @throws ServiceException         - if something fails at Service layer
     */
    @Override
    public User add(User user) throws ServiceException {
        throw new UnsupportedOperationException();
    }
}
